# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
jobs:
  ui_build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "ui/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          command: npm install
          working_directory: ui

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "ui/package.json" }}

      # run tests!
      - run: 
          command: npm test
          working_directory: ui

  
  server_build:
    docker:
      # specify the version you desire here
      - image: circleci/python

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "server/requirements.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run: 
          command: pip install -r requirements.txt
          working_directory: server

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "server/requirements.txt" }}

      # run tests!
      - run: 
          command: pytest
          working_directory: server

  workflows:
    version: 2
    ui_and_server:
      jobs:
        - ui_build
        - server_build